/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#d0c6ad",
        "primary": "#705d00",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#006b71",
        "secondary-fixed": "#ffdad8",
        "inverse-primary": "#e8c426",
        "primary-container": "#ffd93d",
        "on-surface": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed-variant": "#81272b",
        "outline": "#7e7761",
        "surface": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "surface-tint": "#705d00",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fd8585",
        "on-error-container": "#93000a",
        "on-surface-variant": "#4d4633",
        "on-background": "#191c1d",
        "tertiary-fixed-dim": "#00dce7",
        "secondary-fixed-dim": "#ffb3b1",
        "on-tertiary-fixed": "#002022",
        "on-primary-fixed": "#221b00",
        "on-primary-fixed-variant": "#554500",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "background": "#f8f9fa",
        "on-primary-container": "#725e00",
        "surface-container": "#edeeef",
        "primary-fixed": "#ffe173",
        "surface-dim": "#d9dadb",
        "primary-fixed-dim": "#e8c426",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#16f3ff",
        "on-secondary-container": "#741d23",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "tertiary-fixed": "#70f6ff",
        "on-secondary-fixed": "#410007",
        "tertiary": "#00696f",
        "error": "#ba1a1a",
        "secondary": "#a03e40",
        "on-tertiary-fixed-variant": "#004f53"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-mobile": "20px",
        "xs": "4px",
        "margin-desktop": "40px",
        "gutter": "16px",
        "xl": "32px",
        "sm": "12px",
        "lg": "24px",
        "md": "16px"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Be Vietnam Pro"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Be Vietnam Pro"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
